image: 192491131326.dkr.ecr.us-east-1.amazonaws.com/mingle/core/gitlab-builder:latest

stages:
  - build

variables:
  CI_DEBUG_TRACE: "false"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"
  REPOSITORY_HOSTNAME: "192491131326.dkr.ecr.us-east-1.amazonaws.com"

before_script:
  # Environment stuffs
  - >
    [[ "`curl --help 2>&1 >/dev/null ; echo $?`" == "0" ]] &&
    export AWS_ZONE=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone` &&
    export AWS_REGION="`echo \"$AWS_ZONE\" | sed 's/[a-z]$//'`"
  - semver || semver init
  - export VERSION=$(semver format '%M.%m.%p')

py2:
  image: 192491131326.dkr.ecr.us-east-1.amazonaws.com/mingle/core/gitlab-builder-python2:latest
  stage: build
  script:
  - pip install --upgrade --extra-index-url=https://pypi.mingle.awsdev.infor.com -e .
  - s3pypi --bucket pypi.mingle.awsdev.infor.com --index
  tags:
    - cicd
    - ade-mingle-gitlab-runner-docker
  only:
    - develop

py3:
  image: 192491131326.dkr.ecr.us-east-1.amazonaws.com/mingle/core/gitlab-builder-python3:latest
  stage: build
  script:
  - pip install --upgrade --extra-index-url=https://pypi.mingle.awsdev.infor.com -e .
  - s3pypi --bucket pypi.mingle.awsdev.infor.com --index
  tags:
    - cicd
    - ade-mingle-gitlab-runner-docker
  only:
    - develop
