name: Upload Python Package

<<<<<<< Updated upstream
on:
  release:
    types: [created]
=======
#on:
#  release:
#    types: [created,updated]
on: [push]
>>>>>>> Stashed changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_cicd.txt --extra-index-url=http://pypi.dldinternet.com --trusted-host pypi.dldinternet.com
    - name: Build and publish
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: |
        set
        python setup.py clean
        s3pypi --bucket pypi.dldinternet.com --index --check --verbose
